### ISSUE TITLE
Migrate the package to null safety please.

### ISSUE THREAD

**Issue by srihariash999** [prathanbomb/pokedart#10]
I created a PR for this same in which I migrated the package to null safety, Please review it when you can,

#9

**Comment by srihariash999** [comment]
Hey @prathanbomb , thanks for looking into and merging PR #9 

If you can push the same to pub.dev and close this issue that'd be great !

**Comment by prathanbomb** [comment]
There you go @srihariash999 !
I just publish the latest one after a very long time of undated.
https://pub.dev/packages/pokeapi

Many thanks for your PR BTW

**Comment by srihariash999** [comment]
Thanks for accepting my PR and resolving this issue. I can now update my projects dependency from my fork to the package from pub.dev :)
