### ISSUE TITLE
Flutter web support

### ISSUE THREAD

**Issue by CiriousJoker** [prathanbomb/pokedart#3]
This is the issue for pull request #2 to remind you of it.
Once you merged that one, another one will be coming where I changed switch(T) to if(T) since dart2js doesn't support switch(T).

The completely unneccessary dependency on flutter and flutter_test (instead of test) prevented the use of this library inside flutter_web projects.

Also, I added getCommonsList(offset, limit) as a way to only get the common results if that's what you want.

For example, it's overkill to get the results for all 800+ pokemon individually if you're just interested for a list of their ids and names.

Additionally, I moved the switch(T) code into an extra function to dedupe code.

**Comment by prathanbomb** [comment]
Thank you for upgrading this to support dart2js.

**Comment by CiriousJoker** [comment]
Seems like I don't need a second pull request since the old one was "upgraded" when I commited more stuff to my fork.
